import AllRoles from './AllRoles';

const titles = {
  VISA: 'Visa',
};

const roles = {
  newvisa: [AllRoles.VISA.NEWVISA],
  renewal: [AllRoles.VISA.VISARENEWAL],
  cancellation: [AllRoles.VISA.VISACANCELLATION],
  reports: [AllRoles.VISA.REPORTS],
  setup: [AllRoles.VISA.SETUP],
};

export const Visa = [
  {
    component: 'Overview',
    path: '/visa/overview',
    title: titles.VISA,
    permission: roles.newvisa,
    menu: 'Visa',
    submenu: 'Overview',
    key: 'visa',
    icon: 'OverviewIcon',
    parent: true,
  },
  {
    component: 'NewVisa',
    path: '/visa/new-visa',
    title: titles.VISA,
    permission: roles.newvisa,
    key: 'visa',
    menu: 'Visa',
    submenu: 'New Visa',
    icon: 'FacultyIcon',
    parent: true,
  },
  {
    component: 'EditApplication',
    path: '/visa/new-visa/:id',
    title: titles.VISA,
    permission: roles.newvisa,
    key: 'visa',
    menu: 'Visa',
    submenu: 'New Visa',
    icon: 'FacultyIcon',
    parent: false,
  },
  {
    component: 'visaRenewal',
    path: '/visa/renewal',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    icon: 'FacultyIcon',
    parent: true,
  },
  {
    component: 'visaExpired',
    path: '/visa/renewal/expired',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'visaExpiring',
    path: '/visa/renewal/expiring',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'AddVisaRenewal',
    path: '/visa/renewal/expiring/:id',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'AddVisaRenewal',
    path: '/visa/renewal/expired/:id',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'StudentDetails',
    path: '/visa/students/:id',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'Immigration',
    path: '/visa/students/immigration/:id',
    title: titles.VISA,
    permission: roles.renewal,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Renewal',
    parent: false,
  },
  {
    component: 'VisaCancellation',
    path: '/visa/cancellation',
    title: titles.VISA,
    permission: roles.cancellation,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Visa Cancellation',
    icon: 'FacultyIcon',
    parent: true,
  },
  {
    component: 'ReportsList',
    path: '/visa/reports',
    title: titles.VISA,
    permission: roles.reports,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Reports',
    icon: 'ReportsIcon',
    parent: true,
  },
  {
    component: 'AddReports',
    path: '/visa/reports/addnew',
    title: titles.VISA,
    permission: roles.reports,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Reports',
    parent: false,
  },
  {
    component: 'Customize',
    path: '/visa/setup',
    title: titles.VISA,
    permission: roles.setup,
    key: 'visa',
    menu: 'Visa',
    submenu: 'Customize',
    icon: 'SetupIcon',
    parent: true,
  },
];
