export const VISA_RENEWAL_LIST = 'VISA_RENEWAL_LIST';
export const VISA_OVERVIEW = 'VISA_OVERVIEW';
export const NEW_VISA_LIST = 'NEW_VISA_LIST';
export const VISA_EXPIRED_LIST = 'VISA_EXPIRED_LIST';
export const VISA_EXPIRY_LIST = 'VISA_EXPIRY_LIST';
export const EMPTY_VISA_LIST = 'EMPTY_VISA_LIST';